version: '3'

services:
  gofloMainnet:
    build: go-flo
    hostname: goflo
    ports:
      - 7316:7316
      - 127.0.0.1:7317:7317
    volumes:
      - goFloHome:/root/.flod/
    networks:
      - floMainnetNetwork
    args:
      network: mainnet

  gofloTestnet:
    build: go-flo
    hostname: goflo
    ports:
      - 17316:17316
      - 127.0.0.1:17317:17317
    volumes:
      - goFloTestnetHome:/root/.flod/
    networks:
      - floTestnetNetwork
    args:
      network: testnet

networks:
  floMainnetNetwork:
  floTestnetNetwork:

volumes:
  goFloMainnetHome:
  goFloTestnetHome:
